### ISSUE TITLE
[Bug]: I can request a tag containing only _space_

### ISSUE THREAD

**Issue by TeerapatTrepopsakulsin** [SpezSpellz/SpezSpellz#102]
### What happened?

Requesting a tag containing only _space_ shouldn't be allowed.

![image](https://github.com/user-attachments/assets/8554264a-e117-4a8a-90f0-7d2eac9cdf25)

### What did you do to make it happen?

I request a tag of:
name: ` `
description: ` `
(1 space)

### What did you expect to happen?

Same as when you don't type anything, show an error message.

### What browser are you seeing this problem on?

Window 11

**Comment by Pawat-Sarnchawanakit** [comment]
I vouch for freedom, the user can create whatever tag request they like.  
An empty tag sounds cool for void type spells.
