### ISSUE TITLE
[Bug]: Profile picture changed even without Pressing Apply changes button

### ISSUE THREAD

**Issue by Thanawas-Sirilertsathit** [SpezSpellz/SpezSpellz#106]
### What happened?

Profile picture changed when I don't press Apply Changes Button.

### What did you do to make it happen?

* go into general setting
* upload profile picture
* press home button
* check your profile again (It changed to new one)

### What did you expect to happen?

It should apply changes when press the button only. When user cancel the changes by pressing home button, it should revert back to original one.

### What browser are you seeing this problem on?

Chrome Version 131.0.6778.86 (Official Build) (64-bit) (Window AMD64)

**Comment by Pawat-Sarnchawanakit** [comment]
This is intentional
