### ISSUE TITLE
The rating on tags doesn't work the first time I click on it

### ISSUE THREAD

**Issue by jee-gamer** [SpezSpellz/SpezSpellz#59]
The rating on tags doesn't work the first time I click on it
It works the second time
If it's already rated by you then it works the first time.

_Originally posted by @jee-gamer in https://github.com/SpezSpellz/SpezSpellz/issues/58#issuecomment-2424734283_

**Comment by Pawat-Sarnchawanakit** [comment]
Should be fixed in c5ee8e4801532c5703667ba677a561e708189356
