### ISSUE TITLE
Multiple timed notification in upload page

### ISSUE THREAD

**Issue by 0CreepySmile0** [SpezSpellz/SpezSpellz#68]
If user add more than one notification in upload page. Next addition, the repetition box is empty
![image](https://github.com/user-attachments/assets/c089c208-10c5-415f-9219-71baf6b59757)
When there's multiple notification are set. Example in image is "Praying" and "Brewing", when it is 8:40 PM, "Praying" will notify twice in this case.
![image](https://github.com/user-attachments/assets/3f4330bc-2c1a-4d32-a122-f7ab7c8b16c4)

**Comment by Pawat-Sarnchawanakit** [comment]
Should be fixed
